test_dir = "./tests"
pretty_printers_path = "./../prettyPrinters/"
print_stdout = true

[lldb]
python = "python"
lldb_batchmode = "./lldb_batchmode.py"
lldb_lookup = "lldb_lookup"

[gdb]
gdb_lookup = "gdb_lookup"
