name: code quality
on:
    pull_request:

jobs:
    qodana:
        runs-on: ubuntu-latest
        timeout-minutes: 60

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: corretto
                  java-version: 17

            - name: Download
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":resolveDependencies -Pkotlin.incremental=false --no-daemon"

            - name: Generate sources
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":generateLexer :generateParser debugger:generateGrammarSource debugger:generateTestGrammarSource -Pkotlin.incremental=false --no-daemon"

            - name: Qodana
              uses: JetBrains/qodana-action@v2022.3.0
              with:
                  use-caches: false
